from dataclasses import dataclass


@dataclass
class Position:
    symbol: str
        quantity: float
            average_price: float


            class Portfolio:

                def __init__(
                        self,
                                initial_capital: float = 100000,
                                    ):
                                            self.initial_capital = initial_capital
                                                    self.cash = initial_capital
                                                            self.positions: dict[str, Position] = {}
                                                                    self.realized_pnl = 0.0

                                                                        @property
                                                                            def equity(self):
                                                                                    position_value = sum(
                                                                                                position.quantity
                                                                                                            * position.average_price
                                                                                                                        for position in self.positions.values()
                                                                                                                                )

                                                                                                                                        return (
                                                                                                                                                    self.cash
                                                                                                                                                                + position_value
                                                                                                                                                                            + self.realized_pnl
                                                                                                                                                                                    )

                                                                                                                                                                                        def buy(
                                                                                                                                                                                                self,
                                                                                                                                                                                                        symbol: str,
                                                                                                                                                                                                                quantity: float,
                                                                                                                                                                                                                        price: float,
                                                                                                                                                                                                                            ):

                                                                                                                                                                                                                                    if quantity <= 0:
                                                                                                                                                                                                                                                raise ValueError(
                                                                                                                                                                                                                                                                "Quantity must be greater than zero."
                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                    if price <= 0:
                                                                                                                                                                                                                                                                                                raise ValueError(
                                                                                                                                                                                                                                                                                                                "Price must be greater than zero."
                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                    cost = quantity * price

                                                                                                                                                                                                                                                                                                                                            if cost > self.cash:
                                                                                                                                                                                                                                                                                                                                                        raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                        "Insufficient paper-trading cash."
                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                            existing = self.positions.get(symbol)

                                                                                                                                                                                                                                                                                                                                                                                                    if existing is None:
                                                                                                                                                                                                                                                                                                                                                                                                                self.positions[symbol] = Position(
                                                                                                                                                                                                                                                                                                                                                                                                                                symbol=symbol,
                                                                                                                                                                                                                                                                                                                                                                                                                                                quantity=quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                average_price=price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total_quantity = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                existing.quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total_cost = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        existing.quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * existing.average_price
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        + cost
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                existing.quantity = total_quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            existing.average_price = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            total_cost
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            / total_quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.cash -= cost

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def sell(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    symbol: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quantity: float,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price: float,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if symbol not in self.positions:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "No paper position exists."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                position = self.positions[symbol]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if quantity > position.quantity:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Cannot sell more than held quantity."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        proceeds = quantity * price

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pnl = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price - position.average_price
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) * quantity

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.cash += proceeds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.realized_pnl += pnl

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            position.quantity -= quantity

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if position.quantity == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del self.positions[symbol]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def summary(self):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "initial_capital": self.initial_capital,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "cash": self.cash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "realized_pnl": self.realized_pnl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "equity": self.equity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "positions": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        symbol: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "quantity": position.quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "average_price": position.average_price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for symbol, position
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                in self.positions.items()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }