from dataclasses import dataclass

from backend.evidence.models import Evidence


@dataclass
class FusionResult:
    status: str
        score: float
            evidence_count: int
                explanation: str


                class EvidenceFusion:

                    def combine(
                            self,
                                    evidence: list[Evidence],
                                        ) -> FusionResult:

                                                if not evidence:
                                                            return FusionResult(
                                                                            status="INSUFFICIENT DATA",
                                                                                            score=0.0,
                                                                                                            evidence_count=0,
                                                                                                                            explanation="No evidence available.",
                                                                                                                                        )

                                                                                                                                                weighted_score = 0.0
                                                                                                                                                        total_weight = 0.0

                                                                                                                                                                for item in evidence:

                                                                                                                                                                            weight = (
                                                                                                                                                                                            item.reliability
                                                                                                                                                                                                            * item.confidence
                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                    if isinstance(
                                                                                                                                                                                                                                                    item.value,
                                                                                                                                                                                                                                                                    (int, float),
                                                                                                                                                                                                                                                                                ):
                                                                                                                                                                                                                                                                                                weighted_score += (
                                                                                                                                                                                                                                                                                                                    item.value * weight
                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                    total_weight += weight

                                                                                                                                                                                                                                                                                                                                                            if total_weight == 0:
                                                                                                                                                                                                                                                                                                                                                                        return FusionResult(
                                                                                                                                                                                                                                                                                                                                                                                        status="INSUFFICIENT DATA",
                                                                                                                                                                                                                                                                                                                                                                                                        score=0.0,
                                                                                                                                                                                                                                                                                                                                                                                                                        evidence_count=len(evidence),
                                                                                                                                                                                                                                                                                                                                                                                                                                        explanation=(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Evidence contains no "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "usable numeric signals."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    score = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                weighted_score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            / total_weight
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if score > 0.2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status = "BULLISH"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif score < -0.2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status = "BEARISH"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status = "NEUTRAL"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return FusionResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status=status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                score=score,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            evidence_count=len(evidence),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        explanation=(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Evidence combined using "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "reliability and confidence."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )